name = "agentic-workflow"
main = "dist/src/index.js"
compatibility_date = "2024-03-21"
node_compat = true
compatibility_flags = ["nodejs_compat"]

workers_dev = true
account_id = "dc95c232d76cc4df23a5ca452a4046ab"  # Your Cloudflare account ID
zone_id = "1a5dd610e492ab9a1343bb2be936830d"     # Your Cloudflare zone ID if deploying to a custom domain

[build]
command = "npm run build"

# Use module format (ES modules) instead of service-worker format
[build.upload]
format = "modules"

[vars]
NODE_ENV = "production"

# Use the same D1 database as the main project
[[d1_databases]]
binding = "DB"
database_name = "bitebasedb"
database_id = "55ceede4-df98-49fd-9c17-c00d860fba86"

[env.development]
name = "agentic-workflow-dev"
vars = { NODE_ENV = "development" }

[triggers]
crons = ["*/30 * * * *"]  # Run every 30 minutes
